// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02C0OcoShaAPikKss98rcY8z0aCZkswY',
    appId: '1:643982657824:web:78ef884ed1c1f5fa3eaf45',
    messagingSenderId: '643982657824',
    projectId: 'chat-4b50e',
    authDomain: 'chat-4b50e.firebaseapp.com',
    storageBucket: 'chat-4b50e.firebasestorage.app',
    measurementId: 'G-MZJ2G9VDM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCilrUinJanjkTV3zDiqk-6R6Nx0-4o3S4',
    appId: '1:643982657824:android:33572bab16fd8fa03eaf45',
    messagingSenderId: '643982657824',
    projectId: 'chat-4b50e',
    storageBucket: 'chat-4b50e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXHFKG_h3EWi48gET_9D5W2340l3AYqy4',
    appId: '1:643982657824:ios:42bf799deace4dd03eaf45',
    messagingSenderId: '643982657824',
    projectId: 'chat-4b50e',
    storageBucket: 'chat-4b50e.firebasestorage.app',
    iosBundleId: 'com.example.youtubeMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXHFKG_h3EWi48gET_9D5W2340l3AYqy4',
    appId: '1:643982657824:ios:42bf799deace4dd03eaf45',
    messagingSenderId: '643982657824',
    projectId: 'chat-4b50e',
    storageBucket: 'chat-4b50e.firebasestorage.app',
    iosBundleId: 'com.example.youtubeMessengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC02C0OcoShaAPikKss98rcY8z0aCZkswY',
    appId: '1:643982657824:web:57c58187a0083d2b3eaf45',
    messagingSenderId: '643982657824',
    projectId: 'chat-4b50e',
    authDomain: 'chat-4b50e.firebaseapp.com',
    storageBucket: 'chat-4b50e.firebasestorage.app',
    measurementId: 'G-94XQKE9N58',
  );
}
